// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RazorPages.Data;

#nullable disable

namespace RazorPages.Migrations
{
    [DbContext(typeof(SchoolDbContext))]
    [Migration("20250506094220_SeedClass")]
    partial class SeedClass
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RazorPages.Models.Class", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClassName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StudentCount")
                        .HasColumnType("int");

                    b.Property<bool>("isActive")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Classes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClassName = "Class 1",
                            Description = "Class 1 Description",
                            StudentCount = 2,
                            isActive = true
                        },
                        new
                        {
                            Id = 2,
                            ClassName = "Class 2",
                            Description = "Class 2 Description",
                            StudentCount = 4,
                            isActive = true
                        },
                        new
                        {
                            Id = 3,
                            ClassName = "Class 3",
                            Description = "Class 3 Description",
                            StudentCount = 6,
                            isActive = true
                        },
                        new
                        {
                            Id = 4,
                            ClassName = "Class 4",
                            Description = "Class 4 Description",
                            StudentCount = 8,
                            isActive = true
                        },
                        new
                        {
                            Id = 5,
                            ClassName = "Class 5",
                            Description = "Class 5 Description",
                            StudentCount = 10,
                            isActive = true
                        },
                        new
                        {
                            Id = 6,
                            ClassName = "Class 6",
                            Description = "Class 6 Description",
                            StudentCount = 12,
                            isActive = true
                        },
                        new
                        {
                            Id = 7,
                            ClassName = "Class 7",
                            Description = "Class 7 Description",
                            StudentCount = 14,
                            isActive = true
                        },
                        new
                        {
                            Id = 8,
                            ClassName = "Class 8",
                            Description = "Class 8 Description",
                            StudentCount = 16,
                            isActive = true
                        },
                        new
                        {
                            Id = 9,
                            ClassName = "Class 9",
                            Description = "Class 9 Description",
                            StudentCount = 18,
                            isActive = true
                        },
                        new
                        {
                            Id = 10,
                            ClassName = "Class 10",
                            Description = "Class 10 Description",
                            StudentCount = 20,
                            isActive = true
                        },
                        new
                        {
                            Id = 11,
                            ClassName = "Class 11",
                            Description = "Class 11 Description",
                            StudentCount = 22,
                            isActive = true
                        },
                        new
                        {
                            Id = 12,
                            ClassName = "Class 12",
                            Description = "Class 12 Description",
                            StudentCount = 24,
                            isActive = true
                        },
                        new
                        {
                            Id = 13,
                            ClassName = "Class 13",
                            Description = "Class 13 Description",
                            StudentCount = 26,
                            isActive = true
                        },
                        new
                        {
                            Id = 14,
                            ClassName = "Class 14",
                            Description = "Class 14 Description",
                            StudentCount = 28,
                            isActive = true
                        },
                        new
                        {
                            Id = 15,
                            ClassName = "Class 15",
                            Description = "Class 15 Description",
                            StudentCount = 30,
                            isActive = true
                        },
                        new
                        {
                            Id = 16,
                            ClassName = "Class 16",
                            Description = "Class 16 Description",
                            StudentCount = 32,
                            isActive = true
                        },
                        new
                        {
                            Id = 17,
                            ClassName = "Class 17",
                            Description = "Class 17 Description",
                            StudentCount = 34,
                            isActive = true
                        },
                        new
                        {
                            Id = 18,
                            ClassName = "Class 18",
                            Description = "Class 18 Description",
                            StudentCount = 36,
                            isActive = true
                        },
                        new
                        {
                            Id = 19,
                            ClassName = "Class 19",
                            Description = "Class 19 Description",
                            StudentCount = 38,
                            isActive = true
                        },
                        new
                        {
                            Id = 20,
                            ClassName = "Class 20",
                            Description = "Class 20 Description",
                            StudentCount = 40,
                            isActive = true
                        },
                        new
                        {
                            Id = 21,
                            ClassName = "Class 21",
                            Description = "Class 21 Description",
                            StudentCount = 42,
                            isActive = true
                        },
                        new
                        {
                            Id = 22,
                            ClassName = "Class 22",
                            Description = "Class 22 Description",
                            StudentCount = 44,
                            isActive = true
                        },
                        new
                        {
                            Id = 23,
                            ClassName = "Class 23",
                            Description = "Class 23 Description",
                            StudentCount = 46,
                            isActive = true
                        },
                        new
                        {
                            Id = 24,
                            ClassName = "Class 24",
                            Description = "Class 24 Description",
                            StudentCount = 48,
                            isActive = true
                        },
                        new
                        {
                            Id = 25,
                            ClassName = "Class 25",
                            Description = "Class 25 Description",
                            StudentCount = 50,
                            isActive = true
                        },
                        new
                        {
                            Id = 26,
                            ClassName = "Class 26",
                            Description = "Class 26 Description",
                            StudentCount = 52,
                            isActive = true
                        },
                        new
                        {
                            Id = 27,
                            ClassName = "Class 27",
                            Description = "Class 27 Description",
                            StudentCount = 54,
                            isActive = true
                        },
                        new
                        {
                            Id = 28,
                            ClassName = "Class 28",
                            Description = "Class 28 Description",
                            StudentCount = 56,
                            isActive = true
                        },
                        new
                        {
                            Id = 29,
                            ClassName = "Class 29",
                            Description = "Class 29 Description",
                            StudentCount = 58,
                            isActive = true
                        },
                        new
                        {
                            Id = 30,
                            ClassName = "Class 30",
                            Description = "Class 30 Description",
                            StudentCount = 60,
                            isActive = true
                        },
                        new
                        {
                            Id = 31,
                            ClassName = "Class 31",
                            Description = "Class 31 Description",
                            StudentCount = 62,
                            isActive = true
                        },
                        new
                        {
                            Id = 32,
                            ClassName = "Class 32",
                            Description = "Class 32 Description",
                            StudentCount = 64,
                            isActive = true
                        },
                        new
                        {
                            Id = 33,
                            ClassName = "Class 33",
                            Description = "Class 33 Description",
                            StudentCount = 66,
                            isActive = true
                        },
                        new
                        {
                            Id = 34,
                            ClassName = "Class 34",
                            Description = "Class 34 Description",
                            StudentCount = 68,
                            isActive = true
                        },
                        new
                        {
                            Id = 35,
                            ClassName = "Class 35",
                            Description = "Class 35 Description",
                            StudentCount = 70,
                            isActive = true
                        },
                        new
                        {
                            Id = 36,
                            ClassName = "Class 36",
                            Description = "Class 36 Description",
                            StudentCount = 72,
                            isActive = true
                        },
                        new
                        {
                            Id = 37,
                            ClassName = "Class 37",
                            Description = "Class 37 Description",
                            StudentCount = 74,
                            isActive = true
                        },
                        new
                        {
                            Id = 38,
                            ClassName = "Class 38",
                            Description = "Class 38 Description",
                            StudentCount = 76,
                            isActive = true
                        },
                        new
                        {
                            Id = 39,
                            ClassName = "Class 39",
                            Description = "Class 39 Description",
                            StudentCount = 78,
                            isActive = true
                        },
                        new
                        {
                            Id = 40,
                            ClassName = "Class 40",
                            Description = "Class 40 Description",
                            StudentCount = 80,
                            isActive = true
                        },
                        new
                        {
                            Id = 41,
                            ClassName = "Class 41",
                            Description = "Class 41 Description",
                            StudentCount = 82,
                            isActive = true
                        },
                        new
                        {
                            Id = 42,
                            ClassName = "Class 42",
                            Description = "Class 42 Description",
                            StudentCount = 84,
                            isActive = true
                        },
                        new
                        {
                            Id = 43,
                            ClassName = "Class 43",
                            Description = "Class 43 Description",
                            StudentCount = 86,
                            isActive = true
                        },
                        new
                        {
                            Id = 44,
                            ClassName = "Class 44",
                            Description = "Class 44 Description",
                            StudentCount = 88,
                            isActive = true
                        },
                        new
                        {
                            Id = 45,
                            ClassName = "Class 45",
                            Description = "Class 45 Description",
                            StudentCount = 90,
                            isActive = true
                        },
                        new
                        {
                            Id = 46,
                            ClassName = "Class 46",
                            Description = "Class 46 Description",
                            StudentCount = 92,
                            isActive = true
                        },
                        new
                        {
                            Id = 47,
                            ClassName = "Class 47",
                            Description = "Class 47 Description",
                            StudentCount = 94,
                            isActive = true
                        },
                        new
                        {
                            Id = 48,
                            ClassName = "Class 48",
                            Description = "Class 48 Description",
                            StudentCount = 96,
                            isActive = true
                        },
                        new
                        {
                            Id = 49,
                            ClassName = "Class 49",
                            Description = "Class 49 Description",
                            StudentCount = 98,
                            isActive = true
                        },
                        new
                        {
                            Id = 50,
                            ClassName = "Class 50",
                            Description = "Class 50 Description",
                            StudentCount = 100,
                            isActive = true
                        },
                        new
                        {
                            Id = 51,
                            ClassName = "Class 51",
                            Description = "Class 51 Description",
                            StudentCount = 102,
                            isActive = true
                        },
                        new
                        {
                            Id = 52,
                            ClassName = "Class 52",
                            Description = "Class 52 Description",
                            StudentCount = 104,
                            isActive = true
                        },
                        new
                        {
                            Id = 53,
                            ClassName = "Class 53",
                            Description = "Class 53 Description",
                            StudentCount = 106,
                            isActive = true
                        },
                        new
                        {
                            Id = 54,
                            ClassName = "Class 54",
                            Description = "Class 54 Description",
                            StudentCount = 108,
                            isActive = true
                        },
                        new
                        {
                            Id = 55,
                            ClassName = "Class 55",
                            Description = "Class 55 Description",
                            StudentCount = 110,
                            isActive = true
                        },
                        new
                        {
                            Id = 56,
                            ClassName = "Class 56",
                            Description = "Class 56 Description",
                            StudentCount = 112,
                            isActive = true
                        },
                        new
                        {
                            Id = 57,
                            ClassName = "Class 57",
                            Description = "Class 57 Description",
                            StudentCount = 114,
                            isActive = true
                        },
                        new
                        {
                            Id = 58,
                            ClassName = "Class 58",
                            Description = "Class 58 Description",
                            StudentCount = 116,
                            isActive = true
                        },
                        new
                        {
                            Id = 59,
                            ClassName = "Class 59",
                            Description = "Class 59 Description",
                            StudentCount = 118,
                            isActive = true
                        },
                        new
                        {
                            Id = 60,
                            ClassName = "Class 60",
                            Description = "Class 60 Description",
                            StudentCount = 120,
                            isActive = true
                        },
                        new
                        {
                            Id = 61,
                            ClassName = "Class 61",
                            Description = "Class 61 Description",
                            StudentCount = 122,
                            isActive = true
                        },
                        new
                        {
                            Id = 62,
                            ClassName = "Class 62",
                            Description = "Class 62 Description",
                            StudentCount = 124,
                            isActive = true
                        },
                        new
                        {
                            Id = 63,
                            ClassName = "Class 63",
                            Description = "Class 63 Description",
                            StudentCount = 126,
                            isActive = true
                        },
                        new
                        {
                            Id = 64,
                            ClassName = "Class 64",
                            Description = "Class 64 Description",
                            StudentCount = 128,
                            isActive = true
                        },
                        new
                        {
                            Id = 65,
                            ClassName = "Class 65",
                            Description = "Class 65 Description",
                            StudentCount = 130,
                            isActive = true
                        },
                        new
                        {
                            Id = 66,
                            ClassName = "Class 66",
                            Description = "Class 66 Description",
                            StudentCount = 132,
                            isActive = true
                        },
                        new
                        {
                            Id = 67,
                            ClassName = "Class 67",
                            Description = "Class 67 Description",
                            StudentCount = 134,
                            isActive = true
                        },
                        new
                        {
                            Id = 68,
                            ClassName = "Class 68",
                            Description = "Class 68 Description",
                            StudentCount = 136,
                            isActive = true
                        },
                        new
                        {
                            Id = 69,
                            ClassName = "Class 69",
                            Description = "Class 69 Description",
                            StudentCount = 138,
                            isActive = true
                        },
                        new
                        {
                            Id = 70,
                            ClassName = "Class 70",
                            Description = "Class 70 Description",
                            StudentCount = 140,
                            isActive = true
                        },
                        new
                        {
                            Id = 71,
                            ClassName = "Class 71",
                            Description = "Class 71 Description",
                            StudentCount = 142,
                            isActive = true
                        },
                        new
                        {
                            Id = 72,
                            ClassName = "Class 72",
                            Description = "Class 72 Description",
                            StudentCount = 144,
                            isActive = true
                        },
                        new
                        {
                            Id = 73,
                            ClassName = "Class 73",
                            Description = "Class 73 Description",
                            StudentCount = 146,
                            isActive = true
                        },
                        new
                        {
                            Id = 74,
                            ClassName = "Class 74",
                            Description = "Class 74 Description",
                            StudentCount = 148,
                            isActive = true
                        },
                        new
                        {
                            Id = 75,
                            ClassName = "Class 75",
                            Description = "Class 75 Description",
                            StudentCount = 150,
                            isActive = true
                        },
                        new
                        {
                            Id = 76,
                            ClassName = "Class 76",
                            Description = "Class 76 Description",
                            StudentCount = 152,
                            isActive = true
                        },
                        new
                        {
                            Id = 77,
                            ClassName = "Class 77",
                            Description = "Class 77 Description",
                            StudentCount = 154,
                            isActive = true
                        },
                        new
                        {
                            Id = 78,
                            ClassName = "Class 78",
                            Description = "Class 78 Description",
                            StudentCount = 156,
                            isActive = true
                        },
                        new
                        {
                            Id = 79,
                            ClassName = "Class 79",
                            Description = "Class 79 Description",
                            StudentCount = 158,
                            isActive = true
                        },
                        new
                        {
                            Id = 80,
                            ClassName = "Class 80",
                            Description = "Class 80 Description",
                            StudentCount = 160,
                            isActive = true
                        },
                        new
                        {
                            Id = 81,
                            ClassName = "Class 81",
                            Description = "Class 81 Description",
                            StudentCount = 162,
                            isActive = true
                        },
                        new
                        {
                            Id = 82,
                            ClassName = "Class 82",
                            Description = "Class 82 Description",
                            StudentCount = 164,
                            isActive = true
                        },
                        new
                        {
                            Id = 83,
                            ClassName = "Class 83",
                            Description = "Class 83 Description",
                            StudentCount = 166,
                            isActive = true
                        },
                        new
                        {
                            Id = 84,
                            ClassName = "Class 84",
                            Description = "Class 84 Description",
                            StudentCount = 168,
                            isActive = true
                        },
                        new
                        {
                            Id = 85,
                            ClassName = "Class 85",
                            Description = "Class 85 Description",
                            StudentCount = 170,
                            isActive = true
                        },
                        new
                        {
                            Id = 86,
                            ClassName = "Class 86",
                            Description = "Class 86 Description",
                            StudentCount = 172,
                            isActive = true
                        },
                        new
                        {
                            Id = 87,
                            ClassName = "Class 87",
                            Description = "Class 87 Description",
                            StudentCount = 174,
                            isActive = true
                        },
                        new
                        {
                            Id = 88,
                            ClassName = "Class 88",
                            Description = "Class 88 Description",
                            StudentCount = 176,
                            isActive = true
                        },
                        new
                        {
                            Id = 89,
                            ClassName = "Class 89",
                            Description = "Class 89 Description",
                            StudentCount = 178,
                            isActive = true
                        },
                        new
                        {
                            Id = 90,
                            ClassName = "Class 90",
                            Description = "Class 90 Description",
                            StudentCount = 180,
                            isActive = true
                        },
                        new
                        {
                            Id = 91,
                            ClassName = "Class 91",
                            Description = "Class 91 Description",
                            StudentCount = 182,
                            isActive = true
                        },
                        new
                        {
                            Id = 92,
                            ClassName = "Class 92",
                            Description = "Class 92 Description",
                            StudentCount = 184,
                            isActive = true
                        },
                        new
                        {
                            Id = 93,
                            ClassName = "Class 93",
                            Description = "Class 93 Description",
                            StudentCount = 186,
                            isActive = true
                        },
                        new
                        {
                            Id = 94,
                            ClassName = "Class 94",
                            Description = "Class 94 Description",
                            StudentCount = 188,
                            isActive = true
                        },
                        new
                        {
                            Id = 95,
                            ClassName = "Class 95",
                            Description = "Class 95 Description",
                            StudentCount = 190,
                            isActive = true
                        },
                        new
                        {
                            Id = 96,
                            ClassName = "Class 96",
                            Description = "Class 96 Description",
                            StudentCount = 192,
                            isActive = true
                        },
                        new
                        {
                            Id = 97,
                            ClassName = "Class 97",
                            Description = "Class 97 Description",
                            StudentCount = 194,
                            isActive = true
                        },
                        new
                        {
                            Id = 98,
                            ClassName = "Class 98",
                            Description = "Class 98 Description",
                            StudentCount = 196,
                            isActive = true
                        },
                        new
                        {
                            Id = 99,
                            ClassName = "Class 99",
                            Description = "Class 99 Description",
                            StudentCount = 198,
                            isActive = true
                        },
                        new
                        {
                            Id = 100,
                            ClassName = "Class 100",
                            Description = "Class 100 Description",
                            StudentCount = 200,
                            isActive = true
                        },
                        new
                        {
                            Id = 101,
                            ClassName = "Class 101",
                            Description = "Class 101 Description",
                            StudentCount = 202,
                            isActive = true
                        },
                        new
                        {
                            Id = 102,
                            ClassName = "Class 102",
                            Description = "Class 102 Description",
                            StudentCount = 204,
                            isActive = true
                        },
                        new
                        {
                            Id = 103,
                            ClassName = "Class 103",
                            Description = "Class 103 Description",
                            StudentCount = 206,
                            isActive = true
                        },
                        new
                        {
                            Id = 104,
                            ClassName = "Class 104",
                            Description = "Class 104 Description",
                            StudentCount = 208,
                            isActive = true
                        },
                        new
                        {
                            Id = 105,
                            ClassName = "Class 105",
                            Description = "Class 105 Description",
                            StudentCount = 210,
                            isActive = true
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
